---
all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 10.0.200.1
          ansible_user: root
          # SECURITY: Use vault encrypted password or SSH keys instead of plain text
          # ansible_ssh_pass: "{{ vault_ssh_password }}"
          # ansible_ssh_pass: "{{ vault_ssh_password }}"  # TODO: Move to vault
          ansible_ssh_pass: "iamdevil"  # TODO: Move to vault
          # ansible_ssh_private_key_file: "{{ playbook_dir }}/../.ssh/id_rsa"
          
          # Host-specific configuration
          proxmox_node_id: pve
          proxmox_cluster_name: homelab
          
    haos:
      hosts:
        pve:  # Same host but different group for HAOS-specific configurations
          haos_vm_id: 100
          haos_memory: 2048
          haos_cores: 2
          haos_disk_size: 32
          
  vars:
    # Global Configuration
    domain_name: pve.local
    deployment_environment: production
    
    # Security Configuration
    security_hardening:
      enabled: true
      ssh_port: 22
      fail2ban_enabled: true
      firewall_enabled: true
      
    # Monitoring Configuration  
    monitoring:
      enabled: true
      log_retention_days: 30
      metrics_collection: true
      health_checks: true
    
    # NTP Configuration
    ntp_config:
      enabled: true
      servers:
        - pool.ntp.org
        - time.cloudflare.com
        - time.google.com
      timezone: "Asia/Kolkata"  # Change this to your preferred timezone
    
    # Network Configuration for VMs
    network_config:
      # VM Bridge Configuration
      vm_bridge:
        name: vmbr1
        address: 10.0.100.1
        netmask: 255.255.255.0
        network: 10.0.100.0/24
        gateway: 10.0.200.1  # Points to main host IP
        bridge_ports: none
        bridge_stp: off
        bridge_fd: 0
        bridge_vlan_aware: yes
      
      # NAT/Masquerade configuration for internet access
      nat_config:
        enabled: true
        external_interface: vmbr0  # Main bridge interface
        internal_interface: vmbr1  # VM bridge interface
        internal_network: 10.0.100.0/24
      
      # Firewall rules for VM access
      firewall_rules:
        - rule: "ACCEPT"
          source: "10.0.100.0/24"
          dest: any
          comment: "Allow VMs to access internet"
        - rule: "ACCEPT" 
          source: "10.0.0.0/16"
          dest: "10.0.100.0/24"
          comment: "Allow external network to access VMs"
    
    # GPU Passthrough Configuration
    gpu_passthrough:
      enabled: true
      # IOMMU Configuration
      iommu:
        # Set to 'intel_iommu=on' for Intel CPUs or 'amd_iommu=on' for AMD CPUs
        kernel_params: "intel_iommu=on iommu=pt"
        # Alternative for AMD: "amd_iommu=on iommu=pt"
      
      # GPU Configuration
      gpu_config:
        # Automatically detect and configure GPU for passthrough
        auto_detect: true
        # Manual GPU specification (optional, used if auto_detect is false)
        pci_ids:
          - "10de:2204"  # Example: NVIDIA RTX 3080 - replace with your GPU's PCI ID
          - "10de:1aef"  # Example: NVIDIA Audio device - replace with your GPU's audio PCI ID
        
        # Driver blacklisting
        blacklist_drivers:
          - nouveau      # NVIDIA open-source driver
          - nvidia       # NVIDIA proprietary driver
          - nvidia_drm
          - nvidia_modeset
          - nvidia_uvm
          - snd_hda_intel  # Sometimes needed for GPU audio
          # Add more drivers as needed for AMD cards:
          # - radeon
          # - amdgpu
        
        # VFIO driver configuration  
        vfio_drivers:
          - vfio
          - vfio_iommu_type1
          - vfio_pci
          - vfio_virqfd
        
        # Early VFIO binding (recommended for stability)
        early_vfio_binding: true
      
      # VM Configuration hints
      vm_config:
        # Recommended VM settings for GPU passthrough
        machine_type: "q35"
        cpu_type: "host"
        # Enable PCIe for better performance
        pcie: true
        # UEFI BIOS for modern GPU support
        uefi: true