---
galaxy_info:
  author: Homeserver Admin
  description: Deploy Home Assistant OS VM on Proxmox
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
  
dependencies: []
