---
# Handlers for vm_networking role

- name: restart networking
  systemd:
    name: networking
    state: restarted
  listen: "restart networking"

- name: wait for network
  wait_for_connection:
    timeout: 60
    delay: 10
  listen: "wait for network"

- name: save iptables
  shell: |
    iptables-save > /etc/iptables/rules.v4
    ip6tables-save > /etc/iptables/rules.v6
  ignore_errors: true
  listen: "save iptables"
